import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Aswin.S",
      email: "aswin1542000@gmail.com",
      password: bcrypt.hashSync("4444", 8),
      isAdmin: true,
    },
    {
      name: "Priya.S",
      email: "priyas@gmail.com",
      password: bcrypt.hashSync("4444", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "https://m.media-amazon.com/images/I/618Wek95laS._UL1440_.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "https://m.media-amazon.com/images/I/61C9QDGpuLS._UL1440_.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "https://m.media-amazon.com/images/I/61B-Bnpx1IL._UL1440_.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Allen Solley",
      category: "Shirt",
      image: "https://m.media-amazon.com/images/I/71-0gpmRw4L._UL1440_.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "North Republic",
      category: "Shirt",
      image: "https://m.media-amazon.com/images/I/61DGAlvxRLL._UL1440_.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Otto Casuals",
      category: "Shirts",
      image: "https://m.media-amazon.com/images/I/61+AFL31aML._UL1440_.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Ladies collection",
      category: "Churidar",
      image: "https://m.media-amazon.com/images/I/818p2-9KXyL._UL1500_.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
